spring:
  application:
    name: file-service
  # http请求设置
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

# 自动分配端口
server:
  port: 3334
  tomcat.uri-encoding: UTF-8

########################################################################################################################
#### UUID config
########################################################################################################################
uuid:
  data_center_id: 11
  machine_id: 11
